substitutions:
  device_name: "dining-room-switch"
  friendly_name: "Dining Room Switch"
  wifi_ssid: !secret wifi_ssid
  wifi_password: REDACTED
  ota_password: ""
  language: en
  boot_sound: false
  upload_tft_automatically: true

packages:
  remote_package:
    url: https://github.com/edwardtfn/NSPanel-Easy
    ref: latest
    refresh: 300s
    files:
      - nspanel_esphome.yaml