substitutions:
  device_name: "office-light-switch"
  friendly_name: "Office Light Switch"
  wifi_ssid: !secret wifi_ssid
  wifi_password: REDACTED
  ota_password: ""
  language: en
  boot_sound: false
  upload_tft_automatically: true

##### My customization - Start #####
sensor:
  - id: !extend temp_nspanel
    filters:
      - lambda: return x * 9.0 / 5.0 + 32.0;
    unit_of_measurement: "°F"
    accuracy_decimals: 1
##### My customization - End #####

packages:
  remote_package:
    url: https://github.com/edwardtfn/NSPanel-Easy
    ref: latest
    refresh: 300s
    files:
      - nspanel_esphome.yaml
