substitutions:
  device_name: "zenobiahouseesp"
  friendly_name: "Speakeasy Light Switch"
  wifi_ssid: !secret wifi_ssid
  wifi_password: REDACTED
  ota_password: ""
  language: en
  boot_sound: false
  upload_tft_automatically: true

##### My customization - Start #####
ota:
  - id: !extend ota_std
    password: "REDACTED"
##### My customization - End #####
packages:
  remote_package:
    url: https://github.com/edwardtfn/NSPanel-Easy
    ref: latest
    refresh: 300s
    files:
      - nspanel_esphome.yaml
